### ISSUE TITLE
Implement all event handler

### ISSUE THREAD

**Issue by popojargo** [amittleider/AutoFinance.Broker#23]
Hi!

First, thanks for making this project! It really helps to manipulate simple requests with IB API.
I was wondering why a lot of the callback handlers were not implemented?

When some requests are not possible through a controller, I usually call the EClientSocket directly but with the wrapper associated to this EClientSocket, callback handler cannot be mapped. 

If there's no problem with that, I would like to implement all those default handlers so this can be used without specific limitation.

**Comment by amittleider** [comment]
Hello @popojargo 

I'm glad you like the lib! 

Not all the callback handlers are implemented simply because our application that consumes this library does not depend on all of them. 

Your pull requests are certainly welcome, they will move this library closer to having full parity with the EClientSocket and EWrapper. 

I'm available by chat if you'd like to discuss anything. https://discord.gg/pQKX57
